[package]
name = "rustengan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
serde = {version = "1",features = ["derive"]}
serde_json = "1"
ulid = "1.0.0"

[[bin]]
name = "echo"
